### ISSUE TITLE
unzip error~

### ISSUE THREAD

**Issue by bluce-vayn** [cxOrz/pixel_ims_module#1]
Hi,developer! I install the zip file in magisk (install from local) it shows unzip error,my decice is well rooted ~can u help to fix it?my os have the issue of ims service no registered ,cant use volte,and switch the network to 4G,it just has LTE!
  Thank you!

**Comment by bluce-vayn** [comment]
Thank you,i've fixed this installing issue,but it seems  function  doesn't work~ i wil try other ways!

**Comment by cxOrz** [comment]
需要重启生效。
另外：这个unzip error从没遇到过诶，你的magisk版本是多少

**Comment by bluce-vayn** [comment]
哈哈！ 解决了，可能因为打包多次，文件出现套娃现象，好几层！方法是解压后打开到有全部文件路径，然后全选重新打包压缩，这样只有一层了，就可以安装了！我也是看到老外在论坛里的发炎发现的…能安装也重启了，还是定制rom问题，VoLTE 开启不了，而且ims 服务未注册，把卡换到其他手机就没这些问题了！谢谢！
